"""
CoDude — Review Router

Endpoints for the code review API. The main POST /api/v1/review endpoint
is now wired to the real AI service (ReviewService → LangChain → OpenAI).
Sub-endpoints (bugs, security, complexity) remain as stubs until the
individual analysis services are built.

Routes:
    POST /api/v1/review            — Full AI-powered code review
    POST /api/v1/review/bugs       — Bug detection only (stub)
    POST /api/v1/review/security   — Security analysis only (stub)
    POST /api/v1/review/complexity — Complexity analysis only (stub)
"""

import logging

from fastapi import APIRouter, HTTPException, Request

from app.middleware.rate_limiter import limiter
from app.models.review import (
    BugFinding,
    CodeReviewRequest,
    CodeReviewResponse,
    ComplexityResult,
    SecurityFinding,
)
from app.services.review_service import ReviewService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["review"])

# ── Service Instance ────────────────────────────────────────────────────────
# Single ReviewService instance shared across requests.
# In a production app this would be injected via FastAPI's Depends().

_review_service = ReviewService()


# ── Mock Data Generators (for stub endpoints) ───────────────────────────────
# These will be replaced by dedicated AI service calls in later days.


def _mock_bugs() -> list[BugFinding]:
    """Return a realistic list of mock bug findings."""
    return [
        BugFinding(
            line=10,
            severity="medium",
            message="Variable 'x' is defined but never used.",
            suggestion="Remove the unused variable or use it in the logic.",
        ),
        BugFinding(
            line=25,
            severity="high",
            message="Potential division by zero on line 25.",
            suggestion="Add a guard clause to check if the divisor is non-zero.",
        ),
    ]


def _mock_security() -> list[SecurityFinding]:
    """Return a realistic list of mock security findings."""
    return [
        SecurityFinding(
            line=42,
            severity="critical",
            message="User input is passed directly to SQL query without sanitisation.",
            suggestion="Use parameterised queries or an ORM to prevent SQL injection.",
            owasp_category="A03:2021 – Injection",
        ),
    ]


def _mock_complexity() -> ComplexityResult:
    """Return a mock complexity analysis result."""
    return ComplexityResult(
        time_complexity="O(n²)",
        space_complexity="O(n)",
        explanation=(
            "The nested loop iterates over all pairs, resulting in quadratic time. "
            "A hash-map approach could reduce this to O(n)."
        ),
        brute_force_alternative="O(n³) with a triple-nested loop.",
    )


# ── Endpoints ────────────────────────────────────────────────────────────────


@router.post(
    "/review",
    response_model=CodeReviewResponse,
    summary="Full code review",
    description="Analyses code for bugs, security vulnerabilities, and complexity using GPT-4o-mini.",
)
@limiter.limit("10/minute")
async def review_code(request: Request, review_request: CodeReviewRequest) -> CodeReviewResponse:
    """
    Full AI-powered code review endpoint.

    Accepts source code and returns a comprehensive review including
    bug findings, security findings, complexity analysis, and an
    overall quality score — all generated by GPT-4o-mini via LangChain.
    """
    try:
        logger.info(
            "Starting AI review for %s code (%d chars)",
            review_request.language,
            len(review_request.code),
        )
        response = await _review_service.review(review_request)
        logger.info(
            "AI review complete — score: %d, bugs: %d, security: %d",
            response.overall_score,
            len(response.bugs),
            len(response.security),
        )
        return response
    except Exception as exc:
        logger.error("AI review failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=502,
            detail=f"AI service error: {str(exc)}",
        ) from exc


@router.post(
    "/review/bugs",
    response_model=list[BugFinding],
    summary="Bug detection only",
    description="Scans code for bugs and code-quality issues.",
)
async def review_bugs(request: CodeReviewRequest) -> list[BugFinding]:
    """
    Bug-only review endpoint.

    Returns a list of bug findings without security or complexity analysis.
    Useful when the client only needs a quick lint-style check.

    This is currently a STUB — returns mock data.
    """
    return _mock_bugs()


@router.post(
    "/review/security",
    response_model=list[SecurityFinding],
    summary="Security analysis only",
    description="Scans code for security vulnerabilities (OWASP-categorised).",
)
async def review_security(request: CodeReviewRequest) -> list[SecurityFinding]:
    """
    Security-only review endpoint.

    Returns a list of security findings categorised by OWASP Top 10.
    Useful for security-focused audits.

    This is currently a STUB — returns mock data.
    """
    return _mock_security()


@router.post(
    "/review/complexity",
    response_model=ComplexityResult,
    summary="Complexity analysis only",
    description="Analyses time and space complexity of the submitted code.",
)
async def review_complexity(request: CodeReviewRequest) -> ComplexityResult:
    """
    Complexity-only review endpoint.

    Returns Big-O time and space complexity analysis.
    Useful for algorithm optimisation workflows.

    This is currently a STUB — returns mock data.
    """
    return _mock_complexity()
