"""
CoDude — Review Router (Day 12 — Security Report Endpoint)

Endpoints for the code review API. The main POST /api/v1/review endpoint
is now wired to the unified ReviewPipeline (Day 12), which runs:
    1. Language detection
    2. AST analysis (Python)
    3. Regex matching (JS/Java)
    4. OWASP static security scan
    5. Async LLM calls (bugs + security + complexity)
    6. Merge LLM + OWASP security findings
    7. Exploit enrichment (critical/high only, parallel)
    8. Deduplication, sorting, and scoring

Day 12 additions:
    - GET /api/v1/review/{review_id}/security-report endpoint
      Returns a markdown-formatted security report for a completed review

Routes:
    POST /api/v1/review                              — Full pipeline-powered code review
    GET  /api/v1/review/{review_id}/security-report  — Security report (markdown)
    POST /api/v1/review/bugs                         — Bug detection only (stub)
    POST /api/v1/review/security                     — Security analysis only (stub)
    POST /api/v1/review/complexity                   — Complexity analysis only (stub)
"""

import logging

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import PlainTextResponse

from app.middleware.rate_limiter import limiter
from app.models.review import (
    BugFinding,
    CodeReviewRequest,
    CodeReviewResponse,
    ComplexityResult,
    SecurityFinding,
)
from app.services.pipeline import ReviewPipeline, _review_store
from app.services.security.report_generator import SecurityReportGenerator

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["review"])

# ── Pipeline & Report Generator Instances ───────────────────────────────────
# Single instances shared across requests.
# In a production app these would be injected via FastAPI's Depends().

_pipeline = ReviewPipeline()
_report_generator = SecurityReportGenerator()


# ── Mock Data Generators (for stub endpoints) ───────────────────────────────
# These will be replaced by dedicated pipeline sub-calls in later days.


def _mock_bugs() -> list[BugFinding]:
    """Return a realistic list of mock bug findings."""
    return [
        BugFinding(
            line=10,
            severity="medium",
            message="Variable 'x' is defined but never used.",
            suggestion="Remove the unused variable or use it in the logic.",
        ),
        BugFinding(
            line=25,
            severity="high",
            message="Potential division by zero on line 25.",
            suggestion="Add a guard clause to check if the divisor is non-zero.",
        ),
    ]


def _mock_security() -> list[SecurityFinding]:
    """Return a realistic list of mock security findings."""
    return [
        SecurityFinding(
            line=42,
            severity="critical",
            message="User input is passed directly to SQL query without sanitisation.",
            suggestion="Use parameterised queries or an ORM to prevent SQL injection.",
            owasp_category="A03:2021 – Injection",
        ),
    ]


def _mock_complexity() -> ComplexityResult:
    """Return a mock complexity analysis result."""
    return ComplexityResult(
        time_complexity="O(n²)",
        space_complexity="O(n)",
        explanation=(
            "The nested loop iterates over all pairs, resulting in quadratic time. "
            "A hash-map approach could reduce this to O(n)."
        ),
        brute_force_alternative="O(n³) with a triple-nested loop.",
    )


# ── Endpoints ────────────────────────────────────────────────────────────────


@router.post(
    "/review",
    response_model=CodeReviewResponse,
    summary="Full code review",
    description=(
        "Analyses code for bugs, security vulnerabilities, and complexity "
        "using the unified review pipeline (static + LLM)."
    ),
)
@limiter.limit("10/minute")
async def review_code(request: Request, review_request: CodeReviewRequest) -> CodeReviewResponse:
    """
    Full pipeline-powered code review endpoint.

    Accepts source code and returns a comprehensive review including
    bug findings, security findings (with LLM-enhanced exploit scenarios
    for critical/high findings), complexity analysis, overall quality
    score, and processing time — all generated by the unified
    ReviewPipeline (Day 12).
    """
    try:
        logger.info(
            "Review request received — language=%s, code_length=%d",
            review_request.language,
            len(review_request.code),
        )
        response = await _pipeline.run(review_request)
        logger.info(
            "Review complete — score=%d, bugs=%d, security=%d, time=%dms",
            response.overall_score,
            len(response.bugs),
            len(response.security),
            response.processing_time_ms,
        )
        return response
    except Exception as exc:
        logger.error("Pipeline failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=502,
            detail=f"AI service error: {str(exc)}",
        ) from exc


@router.get(
    "/review/{review_id}/security-report",
    response_class=PlainTextResponse,
    summary="Security report (markdown)",
    description=(
        "Returns a markdown-formatted security report for a completed review. "
        "Use 'latest' as review_id to get the most recent review's report."
    ),
)
async def get_security_report(review_id: str) -> PlainTextResponse:
    """
    Security report endpoint (Day 12).

    Generates a professional markdown security report for the given review.
    The report includes:
        - Severity summary table
        - One section per finding with exploit scenario and remediation code
        - CWE/OWASP reference links

    Args:
        review_id: The review ID (numeric) or "latest" for the most recent.

    Returns:
        Markdown-formatted security report as text/markdown.

    Raises:
        404 if no review with the given ID exists.
    """
    review = _review_store.get(review_id)
    if review is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Review '{review_id}' not found. Run a review first via "
                "POST /api/v1/review, then use the returned review_id or 'latest'."
            ),
        )

    markdown = _report_generator.generate_markdown(review.security)
    logger.info(
        "Security report generated for review_id=%s — %d findings, %d chars",
        review_id,
        len(review.security),
        len(markdown),
    )
    return PlainTextResponse(content=markdown, media_type="text/markdown")


@router.post(
    "/review/bugs",
    response_model=list[BugFinding],
    summary="Bug detection only",
    description="Scans code for bugs and code-quality issues.",
)
async def review_bugs(request: CodeReviewRequest) -> list[BugFinding]:
    """
    Bug-only review endpoint.

    Returns a list of bug findings without security or complexity analysis.
    Useful when the client only needs a quick lint-style check.

    This is currently a STUB — returns mock data.
    """
    return _mock_bugs()


@router.post(
    "/review/security",
    response_model=list[SecurityFinding],
    summary="Security analysis only",
    description="Scans code for security vulnerabilities (OWASP-categorised).",
)
async def review_security(request: CodeReviewRequest) -> list[SecurityFinding]:
    """
    Security-only review endpoint.

    Returns a list of security findings categorised by OWASP Top 10.
    Useful for security-focused audits.

    This is currently a STUB — returns mock data.
    """
    return _mock_security()


@router.post(
    "/review/complexity",
    response_model=ComplexityResult,
    summary="Complexity analysis only",
    description="Analyses time and space complexity of the submitted code.",
)
async def review_complexity(request: CodeReviewRequest) -> ComplexityResult:
    """
    Complexity-only review endpoint.

    Returns Big-O time and space complexity analysis.
    Useful for algorithm optimisation workflows.

    This is currently a STUB — returns mock data.
    """
    return _mock_complexity()

