"""
CoDude — Review Router (Day 15 — Visualization Data & Complexity Summary)

Endpoints for the code review API. The main POST /api/v1/review endpoint
is now wired to the unified ReviewPipeline, which runs:
    1. Language detection
    2. AST analysis (Python)
    3. Regex matching (JS/Java)
    4. OWASP static security scan
    5. Per-function complexity annotation (Day 13)
    6. Async LLM calls (bugs + security + complexity)
    7. Merge LLM + OWASP security findings
    8. Exploit enrichment (critical/high only, parallel)
    9. Deduplication, sorting, and scoring

Day 13 additions:
    - POST /api/v1/analyze/complexity endpoint
      Returns per-function complexity annotations (faster, cheaper)

Day 15 additions:
    - /analyze/complexity now returns ComplexityResult with visualization + summary
    - GET /api/v1/analyze/complexity/summary — Fetches just the complexity summary

Routes:
    POST /api/v1/review                              — Full pipeline-powered code review
    GET  /api/v1/review/{review_id}/security-report  — Security report (markdown)
    POST /api/v1/analyze/complexity                   — Per-function complexity + viz + summary
    GET  /api/v1/analyze/complexity/summary           — Complexity summary only
    POST /api/v1/review/bugs                         — Bug detection only (stub)
    POST /api/v1/review/security                     — Security analysis only (stub)
    POST /api/v1/review/complexity                   — Complexity analysis only (stub)
"""

import logging

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import PlainTextResponse

from app.middleware.rate_limiter import limiter
from app.models.review import (
    BugFinding,
    CodeReviewRequest,
    CodeReviewResponse,
    ComplexityResult,
    FunctionComplexity,
    SecurityFinding,
)
from app.services.complexity import ComplexityService, ComplexityVisualizer
from app.services.complexity.summary_generator import generate_summary
from app.services.pipeline import ReviewPipeline, _review_store
from app.services.security.report_generator import SecurityReportGenerator

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["review"])

# ── Pipeline & Report Generator Instances ───────────────────────────────────
# Single instances shared across requests.
# In a production app these would be injected via FastAPI's Depends().

_pipeline = ReviewPipeline()
_report_generator = SecurityReportGenerator()
_complexity_service = ComplexityService()


# ── Mock Data Generators (for stub endpoints) ───────────────────────────────
# These will be replaced by dedicated pipeline sub-calls in later days.


def _mock_bugs() -> list[BugFinding]:
    """Return a realistic list of mock bug findings."""
    return [
        BugFinding(
            line=10,
            severity="medium",
            message="Variable 'x' is defined but never used.",
            suggestion="Remove the unused variable or use it in the logic.",
        ),
        BugFinding(
            line=25,
            severity="high",
            message="Potential division by zero on line 25.",
            suggestion="Add a guard clause to check if the divisor is non-zero.",
        ),
    ]


def _mock_security() -> list[SecurityFinding]:
    """Return a realistic list of mock security findings."""
    return [
        SecurityFinding(
            line=42,
            severity="critical",
            message="User input is passed directly to SQL query without sanitisation.",
            suggestion="Use parameterised queries or an ORM to prevent SQL injection.",
            owasp_category="A03:2021 – Injection",
        ),
    ]


def _mock_complexity() -> ComplexityResult:
    """Return a mock complexity analysis result."""
    return ComplexityResult(
        time_complexity="O(n²)",
        space_complexity="O(n)",
        explanation=(
            "The nested loop iterates over all pairs, resulting in quadratic time. "
            "A hash-map approach could reduce this to O(n)."
        ),
        brute_force_alternative="O(n³) with a triple-nested loop.",
    )


# ── Endpoints ────────────────────────────────────────────────────────────────


@router.post(
    "/review",
    response_model=CodeReviewResponse,
    summary="Full code review",
    description=(
        "Analyses code for bugs, security vulnerabilities, and complexity "
        "using the unified review pipeline (static + LLM)."
    ),
)
@limiter.limit("10/minute")
async def review_code(request: Request, review_request: CodeReviewRequest) -> CodeReviewResponse:
    """
    Full pipeline-powered code review endpoint.

    Accepts source code and returns a comprehensive review including
    bug findings, security findings (with LLM-enhanced exploit scenarios
    for critical/high findings), complexity analysis, overall quality
    score, and processing time — all generated by the unified
    ReviewPipeline (Day 12).
    """
    try:
        logger.info(
            "Review request received — language=%s, code_length=%d",
            review_request.language,
            len(review_request.code),
        )
        response = await _pipeline.run(review_request)
        logger.info(
            "Review complete — score=%d, bugs=%d, security=%d, time=%dms",
            response.overall_score,
            len(response.bugs),
            len(response.security),
            response.processing_time_ms,
        )
        return response
    except Exception as exc:
        logger.error("Pipeline failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=502,
            detail=f"AI service error: {str(exc)}",
        ) from exc


@router.get(
    "/review/{review_id}/security-report",
    response_class=PlainTextResponse,
    summary="Security report (markdown)",
    description=(
        "Returns a markdown-formatted security report for a completed review. "
        "Use 'latest' as review_id to get the most recent review's report."
    ),
)
async def get_security_report(review_id: str) -> PlainTextResponse:
    """
    Security report endpoint (Day 12).

    Generates a professional markdown security report for the given review.
    The report includes:
        - Severity summary table
        - One section per finding with exploit scenario and remediation code
        - CWE/OWASP reference links

    Args:
        review_id: The review ID (numeric) or "latest" for the most recent.

    Returns:
        Markdown-formatted security report as text/markdown.

    Raises:
        404 if no review with the given ID exists.
    """
    review = _review_store.get(review_id)
    if review is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Review '{review_id}' not found. Run a review first via "
                "POST /api/v1/review, then use the returned review_id or 'latest'."
            ),
        )

    markdown = _report_generator.generate_markdown(review.security)
    logger.info(
        "Security report generated for review_id=%s — %d findings, %d chars",
        review_id,
        len(review.security),
        len(markdown),
    )
    return PlainTextResponse(content=markdown, media_type="text/markdown")


@router.post(
    "/review/bugs",
    response_model=list[BugFinding],
    summary="Bug detection only",
    description="Scans code for bugs and code-quality issues.",
)
async def review_bugs(request: CodeReviewRequest) -> list[BugFinding]:
    """
    Bug-only review endpoint.

    Returns a list of bug findings without security or complexity analysis.
    Useful when the client only needs a quick lint-style check.

    This is currently a STUB — returns mock data.
    """
    return _mock_bugs()


@router.post(
    "/review/security",
    response_model=list[SecurityFinding],
    summary="Security analysis only",
    description="Scans code for security vulnerabilities (OWASP-categorised).",
)
async def review_security(request: CodeReviewRequest) -> list[SecurityFinding]:
    """
    Security-only review endpoint.

    Returns a list of security findings categorised by OWASP Top 10.
    Useful for security-focused audits.

    This is currently a STUB — returns mock data.
    """
    return _mock_security()


@router.post(
    "/review/complexity",
    response_model=ComplexityResult,
    summary="Complexity analysis only",
    description="Analyses time and space complexity of the submitted code.",
)
async def review_complexity(request: CodeReviewRequest) -> ComplexityResult:
    """
    Complexity-only review endpoint.

    Returns Big-O time and space complexity analysis.
    Useful for algorithm optimisation workflows.

    This is currently a STUB — returns mock data.
    """
    return _mock_complexity()


@router.post(
    "/analyze/complexity",
    response_model=ComplexityResult,
    summary="Per-function complexity analysis with visualization",
    description=(
        "Analyzes time and space complexity for each function in the submitted "
        "code using AST pattern matching with LLM fallback for ambiguous cases. "
        "Returns per-function annotations, visualization-ready chart data with "
        "numeric complexity scores, and an LLM-generated executive summary. "
        "Faster and cheaper than a full review when you only need complexity."
    ),
)
@limiter.limit("20/minute")
async def analyze_complexity(
    request: Request, review_request: CodeReviewRequest
) -> ComplexityResult:
    """
    Per-function complexity analysis endpoint (Day 15).

    Uses a hybrid approach:
        - AST pattern matching for 90% of cases (free, <10ms)
        - LLM fallback for low-confidence functions (~$0.002/call)

    Returns a ComplexityResult with:
        - function_complexities:       per-function annotations
        - optimization_opportunities:  brute-force → optimal suggestions
        - visualization:               chart-ready data with numeric scores
        - summary:                     LLM-generated executive summary

    Args:
        review_request: Code review request with code and language.

    Returns:
        ComplexityResult with visualization data and narrative summary.
    """
    try:
        logger.info(
            "Complexity analysis request — language=%s, code_length=%d",
            review_request.language,
            len(review_request.code),
        )
        function_complexities, optimization_opportunities = (
            await _complexity_service.analyze(
                review_request.code, review_request.language
            )
        )

        # Build visualization data (sync, <1ms)
        visualization = ComplexityVisualizer.build(function_complexities)

        # Determine overall complexity from functions
        if function_complexities:
            from app.services.complexity.complexity_visualizer import complexity_to_score
            worst = max(
                function_complexities,
                key=lambda f: complexity_to_score(f.time_complexity),
            )
            overall_time = worst.time_complexity
            overall_space = worst.space_complexity
        else:
            overall_time = "O(1)"
            overall_space = "O(1)"

        result = ComplexityResult(
            time_complexity=overall_time,
            space_complexity=overall_space,
            explanation="Per-function complexity analysis.",
            function_complexities=function_complexities,
            optimization_opportunities=optimization_opportunities,
            visualization=visualization,
        )

        # Generate narrative summary (async LLM)
        try:
            result.summary = await generate_summary(result)
        except Exception as exc:
            logger.warning("Summary generation failed: %s", exc)

        logger.info(
            "Complexity analysis complete — %d function(s), viz=%s, summary=%s",
            len(function_complexities),
            "yes" if visualization else "no",
            "yes" if result.summary else "no",
        )
        return result
    except Exception as exc:
        logger.error("Complexity analysis failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=502,
            detail=f"Analysis error: {str(exc)}",
        ) from exc


@router.get(
    "/analyze/complexity/summary",
    response_class=PlainTextResponse,
    summary="Complexity summary only",
    description=(
        "Returns just the plain-English executive summary from the most "
        "recent complexity analysis. Run POST /api/v1/analyze/complexity "
        "first to generate the summary."
    ),
)
async def get_complexity_summary() -> PlainTextResponse:
    """
    Complexity summary endpoint (Day 15).

    Returns the LLM-generated narrative summary from the most recent
    full review. The summary is a 3–4 sentence plain-English paragraph
    suitable for display in the frontend.

    Returns:
        Plain-text complexity summary.

    Raises:
        404 if no review has been run yet.
    """
    review = _review_store.get("latest")
    if review is None or review.complexity is None:
        raise HTTPException(
            status_code=404,
            detail=(
                "No complexity analysis found. Run a review first via "
                "POST /api/v1/review or POST /api/v1/analyze/complexity."
            ),
        )

    summary = review.complexity.summary
    if not summary:
        raise HTTPException(
            status_code=404,
            detail="Complexity summary not yet generated for this review.",
        )

    return PlainTextResponse(content=summary, media_type="text/plain")
